import { StyleSheet } from 'react-native';

export const detailPanelStyles = StyleSheet.create({
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.6)', // Przyciemnione tło
        justifyContent: 'center',
        alignItems: 'center',
    },
    panelContainer: {
        width: '90%',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 8,
        alignItems: 'center',
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#F3F4F6',
        borderRadius: 50,
        padding: 8,
        elevation: 3,
    },
    editIcon: {
        position: 'absolute',
        top: 10,
        right: 60,
        backgroundColor: '#F3F4F6',
        borderRadius: 50,
        padding: 8,
        elevation: 3,
    },
    placeTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
        textAlign: 'center',
        marginBottom: 20,
        marginTop: 15,
    },
    imageContainer: {
        width: '100%',
        height: 200,
        backgroundColor: '#F9FAFB',
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 6,
    },
    placeImage: {
        width: '100%',
        height: '100%',
        borderRadius: 15,
    },
    imagePlaceholderText: {
        fontSize: 16,
        color: '#9CA3AF',
        fontStyle: 'italic',
    },
    favoriteIcon: {
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 0,
        borderRadius: 50,
        width: 60,
        height: 60,
        backgroundColor: '#FEE2E2', // Jasny czerwony
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    navigateButton: {
        backgroundColor: '#EF4444',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        width: '100%',
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 10,
    },
    navigateButtonText: {
        color: '#FFF',
        fontSize: 18,
        fontWeight: '600',
    },
    input: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        padding: 10,
        marginBottom: 15,
        backgroundColor: '#F9FAFB',
    },
    saveButton: {
        backgroundColor: '#3B82F6', // Niebieski dla zapisu
        width: '48%',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    saveButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '600',
    },
    cancelButton: {
        backgroundColor: '#D1D5DB',
        width: '48%',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    cancelButtonText: {
        color: '#333',
        fontSize: 16,
        fontWeight: '600',
    },
    editPanel: {
        width: '100%',
        padding: 15,
        marginTop: 10,
        borderRadius: 10,
        backgroundColor: '#F9FAFB',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    editInput: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 8,
        padding: 10,
        marginBottom: 15,
        backgroundColor: '#FFFFFF',
    },
    editActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 15,
    },
    editSaveButton: {
        flex: 1,
        backgroundColor: '#3B82F6',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        marginRight: 10,
    },
    editCancelButton: {
        flex: 1,
        backgroundColor: '#D1D5DB',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    editButtonText: {
        color: '#FFF',
        fontSize: 16,
        fontWeight: '600',
    },
    descriptionContainer: {
        width: '100%',
        backgroundColor: '#F9FAFB', // Subtelne tło
        borderRadius: 12,
        padding: 15,
        marginVertical: 15, // Odstęp od innych elementów
        borderWidth: 1,
        borderColor: '#E5E7EB', // Delikatna ramka
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    descriptionText: {
        fontSize: 16,
        color: '#374151', // Ciemniejszy tekst dla lepszej czytelności
        lineHeight: 22, // Większa odległość między wierszami
        fontStyle: 'italic', // Dodatkowy akcent
    },

});
