import { StyleSheet } from 'react-native';

export const journeyPanelStyles = StyleSheet.create({
    panelContainer: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        padding: 40,
        marginHorizontal: 15,
        marginVertical: 60,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 5,
    },
    title: {
        fontSize: 22,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 20,
        color: '#1F2937',
    },
    subTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 10,
        textAlign: 'left',
    },
    itemContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 10,
        backgroundColor: '#F3F4F6',
        borderRadius: 10,
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    placeName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#33673c',
        marginBottom: 4,
    },
    placeDescription: {
        fontSize: 14,
        color: '#6B7280',
    },
    noJourney: {
        fontSize: 16,
        fontStyle: 'italic',
        color: '#9CA3AF',
        textAlign: 'center',
        marginTop: 20,
    },
    searchInput: {
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 10,
        padding: 12,
        backgroundColor: '#F9FAFB',
        fontSize: 16,
        marginBottom: 20,
    },
    searchToggleButton: {
        backgroundColor: '#33673c',
        paddingVertical: 12,
        paddingHorizontal: 25,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    searchToggleButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '700',
    },
    resultList: {
        maxHeight: '60%',
    },
});
